Update bootstrap

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -28,14 +28,10 @@ fi
 # use local nixpkgs
 if [ -z "${NIXPKGS:-}" ]; then
   printf "\033[94mInstalling canonical nixpkgs...\n\033[0m"
-
   if ! NIXPKGS=$(nix eval --raw --impure \
     --expr 'let flake = builtins.getFlake "github:marksisson/parts"; in flake.inputs.nixpkgs.outPath'
-  ); then
-    echo "Failed to fetch nixpkgs (GitHub rate limit?)" >&2
-    exit 1
+  ); then echo "Failed to fetch nixpkgs (GitHub rate limit?)" >&2; exit 1
   fi
-
   export NIXPKGS
 fi
 
